DNM/apps/gallery/urls.py
# gallery/urls.py

from django.conf.urls import patterns, url

from DNM.apps.gallery import views


urlpatterns = patterns('',
    url(
        regex=r'^(?P<pk>\d+)/ajax-upload/$',
        view=views.AjaxPhotoUploadView.as_view(),
        name='ajax_photo_upload_view',
    ),
    url(r'^album_list/$', views.AlbumListView.as_view(), name='album_list'),
    url(r'^photolist/(?P<id>\d+)$', views.PhotoListView.as_view(), name='photo_list'),

    url(r'^album_add/$', views.AlbumCreate.as_view(), name='album_create'),
    url(r'^album_edit/(?P<pk>\d+)$', views.AlbumEdit.as_view(), name='album_edit'),
    url(r'^set_cover_photo/(?P<album_id>\d+)/(?P<photo_id>\d+)$', views.set_cover_photo, name='set_cover_photo'),

    )

DNM/apps/news/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from DNM.apps.news import views


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^(?P<news_id>|None|\d+)/edit$', views.edit, name='edit'),
                       url(r'^(?P<news_id>\d+)/$', views.view, name='view'),
                       url(r'^(?P<news_id>|None|\d+)/delete$', views.delete, name='delete'),
                       url(r'^(?P<news_id>|None|\d+)/save/$', views.save, name='save')
)

DNM/apps/signup/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from DNM.apps.signup.views import *


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^(?P<event_id>|None|\d+)/signup/$', Save, name='save'),
                       url(r'^(?P<signup_id>|None|\d+)/edit/$', Edit, name='edit'),
                       url(r'^(?P<signup_id>|None|\d+)/(?P<event_id>|None|\d+)/remove/$', Remove, name='remove')
)

DNM/urls.py
from django.conf.urls import patterns, include, url

from DNM import views
from DNM.apps.news.events.views import export
from DNM.apps.static_pages.forms import editpage
from DNM.apps.static_pages.views import page
import settings




# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()
from DNM.settings import MEDIA_ROOT

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'DNM.views.home', name='home'),
                       # url(r'^DNM/', include('DNM.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       url(r'^statistics/', views.statistics, name="statistics"),
                       url(r'^contact/', views.contact, name="contact"),
                       url(r'^editpage/(?P<page_id>\w+)$', editpage, name="editpage"),

                       url(r'^page/(?P<page_id>\w+)$', page, name="page"),

                       url(r'^news/', include('DNM.apps.news.urls', namespace='news')),
                       url(r'^gallery/', include('DNM.apps.gallery.urls', namespace='gallery')),

                       url(r'^event/', include('DNM.apps.news.events.urls', namespace='event')),
                       url(r'^UserInformation/', include('DNM.apps.members.urls', namespace='UserInformation')),
                       url(r'^signup/', include('DNM.apps.signup.urls', namespace='signup')),
                       url(r'^klotterplanket/', include('DNM.apps.klotter.urls', namespace='klotter')),


                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
                       url(r'^logout/$', views.logout_, name="logout"),

                       url(r'^$', views.base, name="base"),


                       # (r'^admin/(.*)', admin.site.root),


                       url(r'^event/export/', export, name="event_ics_export"),


                       url(r'^user/password/reset/$',
                           'django.contrib.auth.views.password_reset',
                           {'post_reset_redirect': '/user/password/reset/done/'},
                           name="password_reset"),
                       (r'^user/password/reset/done/$',
                        'django.contrib.auth.views.password_reset_done'),
                       (r'^user/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                        'django.contrib.auth.views.password_reset_confirm',
                        {'post_reset_redirect': '/user/password/done/'}),
                       (r'^user/password/done/$',
                        'django.contrib.auth.views.password_reset_complete'),
                       (r'^summernote/', include('django_summernote.urls')),
                        url(r'^changeLanguage/(?P<language_code>\w+)', views.changeLanguage ,name="changeLanguage"),

)
if settings.DEBUG:
    urlpatterns += patterns(
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': MEDIA_ROOT, 'show_indexes': True}), )

DNM/apps/gallery/models.py
from model_utils.models import TimeStampedModel
from taggit.managers import TaggableManager
from DNM.settings import MEDIA_ROOT
from django.utils.translation import ugettext as _
__author__ = 'eaura'
# gallery/models.py
from django.contrib.auth.models import *
class Album(TimeStampedModel):
    def __unicode__(self):
        return self.title
    title = models.CharField(max_length=250, verbose_name=_(u'Titel'))
    description = models.TextField(blank=True, null=True, verbose_name=_(u'Beskrivning'))
    cover_photo = models.ForeignKey('Photo', related_name='+', blank=True,
                                    null=True)
    is_public = models.BooleanField(default=True)
    date_added = models.DateField(null=True, blank=True)
    tags = TaggableManager(blank=True, help_text=None)
    order = models.PositiveIntegerField(default=9999)


class Photo(TimeStampedModel):
    def __unicode__(self):
        return self.file.url
    album = models.ForeignKey(Album)
    file = models.ImageField(upload_to='photos')
    description = models.TextField(blank=True, null=True)
    is_public = models.BooleanField(default=True)
    tags = TaggableManager(blank=True, help_text=None)

DNM/apps/news/models.py
# coding=utf-8
from django.db import models
from model_utils.managers import InheritanceManager
from django.utils.translation import ugettext as _

__author__ = 'eaura'

from DNM.apps.members.models import *

class Post(models.Model):
    objects = InheritanceManager()
    name = models.CharField(max_length=500, verbose_name=_('Namn'))
    description = models.TextField(verbose_name=_('Beskrivning'))
    created = models.DateTimeField(auto_now_add=True)
    member = models.ForeignKey(Member)
    updated = models.DateTimeField(auto_now=True)

    def getMonth(self):
        return self.created.strftime('%B')



class News(Post):
    def __unicode_Event_(self):
        return self.name

DNM/apps/gallery/forms.py
from django import forms
from django.core.exceptions import ValidationError

from DNM.apps.gallery.models import Album


class AlbumForm(forms.ModelForm):



    class Meta:
        fields = ['title','description']
        model = Album

DNM/apps/klotter/forms.py
from django.forms import ModelForm
from DNM.apps.klotter.models import KlotterPost
from django_summernote.widgets import SummernoteWidget
__author__ = 'eaura'


class KlotterForm(ModelForm):
    class Meta:
        exclude = ('member','parent')
        model = KlotterPost
        widgets = {
            'text': SummernoteWidget(attrs={ 'width': '100%'}),
        }

DNM/apps/news/events/forms.py
from DNM.apps.news.forms import *
from DNM.apps.news.events.models import *
from functools import partial
from django.forms import DateTimeInput,DateTimeField



DateTimeInput = partial(DateTimeInput, {'class': 'datepicker'})

class EventForm(NewsForm):
    date = DateTimeField(input_formats=('%d.%m.%Y %H:%M',),widget=DateTimeInput(format="%d.%m.%Y %H:%M"))
    deadline = DateTimeField(input_formats=('%d.%m.%Y %H:%M',),widget=DateTimeInput(format="%d.%m.%Y %H:%M"))

    class Meta:
        exclude = ('member','madeByAdmin')
        model = Event
        widgets = {
            'description': SummernoteWidget(attrs={ 'width': '100%'}),

        }

DNM/apps/news/forms.py
from django.forms import ModelForm
from django.db import models
from django.utils import timezone
from django import forms
from datetime import timedelta
from DNM.apps.news.models import News
from django.contrib.admin.widgets import FilteredSelectMultiple
from django_summernote.widgets import SummernoteWidget

class NewsForm(ModelForm):
    class Meta:
        exclude = ('member',)
        model = News
        widgets = {
            'description': SummernoteWidget(attrs={'width': '100%'}),
        }

DNM/apps/gallery/views.py
# gallery/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from django.views.generic import View, ListView
from django.views.generic.edit import CreateView,UpdateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone

from braces.views import (
    AjaxResponseMixin,
    JSONResponseMixin,
    LoginRequiredMixin,
    SuperuserRequiredMixin,
)

from DNM.apps.gallery.models import Album, Photo
from DNM.apps.gallery.forms import AlbumForm
from django.utils.translation import ugettext as _
class AlbumCreate(CreateView):
    form_class = AlbumForm
    success_url = '/gallery/album_list/'
    template_name = 'gallery/album_new.html'


class AlbumEdit(UpdateView):
    form_class = AlbumForm
    success_url = '/gallery/album_list/'
    template_name = 'gallery/album_edit.html'
    def get_queryset(self,**kwargs):
           # query_set = super(ModelxUpdateView, self).get_queryset().filter(user=self.request.user)
           query_set = Album.objects.filter(pk=self.kwargs['pk'])
           return query_set

class AlbumListView(ListView):

    model = Album

    def get_context_data(self, **kwargs):
        context = super(AlbumListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class PhotoListView(ListView):

    model = Photo


    def get_queryset(self, **kwargs):
        return Photo.objects.filter(album=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        context = super(PhotoListView, self).get_context_data(**kwargs)
        album = Album.objects.get(pk=self.kwargs['id'])
        context['album'] = album
        context['now'] = timezone.now()
        return context

class AjaxPhotoUploadView(LoginRequiredMixin,
                    SuperuserRequiredMixin,
                    JSONResponseMixin,
                    AjaxResponseMixin,
                    View):
    """
    View for uploading photos via AJAX.
    """
    def post_ajax(self, request, *args, **kwargs):
        try:
            album = Album.objects.get(pk=kwargs.get('pk'))
        except Album.DoesNotExist:
            error_dict = {'message': _('Fann inte albumet.')}
            return self.render_json_response(error_dict, status=404)

        uploaded_file = request.FILES['file']
        photo = Photo.objects.create(album=album, file=uploaded_file)
        photo.save()
        response_dict = {
            'message': _('Filen laddades upp!'),
        }

        return self.render_json_response(response_dict, status=200)


def set_cover_photo(request, album_id,photo_id):
    album =Album.objects.get(pk=album_id)
    album.cover_photo=Photo.objects.get(pk=photo_id)
    album.save()

    return HttpResponseRedirect(reverse('gallery:album_edit', args=(album_id)))

DNM/apps/klotter/views.py
# coding=utf-8
# -*- coding: utf-8 -*-
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from endless_pagination.decorators import page_template

from DNM.apps.klotter.forms import KlotterForm
from DNM.apps.klotter.models import KlotterPost, KlotterVote
from django.utils.translation import ugettext as _

__author__ = 'eaura'


@login_required
@page_template('klotter/klotter_page.html')  # just add this decorator
def klotterplanket(request,template='klotter.html', extra_context=None):

    if request.method == 'POST':
        form = KlotterForm(request.POST, instance=KlotterPost())
        if form.is_valid():
            klotter = form.save(commit=False)
            klotter.member = get_user(request)
            if request.POST.get("parent")!=u'None':
                parent = KlotterPost.objects.get(pk=request.POST.get("parent"))
                klotter.parent = parent
            messages.add_message(request, messages.SUCCESS, _('Kommentar sparad'))
            klotter.save()
        else:
            messages.add_message(request, messages.ERROR, _(u'Kunde inte spara inlägg. Kolla att alla obligatoriska fält är ifyllda'))

    klotter_list = [node.get_descendants(include_self=True)
         for node in KlotterPost.objects.filter(level__lte=0)]
    klotter = KlotterPost()
    if not get_user(request).grad.isGuest():
        klotter.writer = get_user(request).get_full_name
    form = KlotterForm(instance=klotter)

    context = {'nodes': klotter_list, 'form': form}
    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


@login_required
def vote(request, klotter_id):
    klotter = KlotterPost.objects.get(pk=klotter_id)
    vote, created =  KlotterVote.objects.get_or_create(member = request.user, klotter = klotter)
    if not created:
        messages.add_message(request, messages.ERROR, _(u'En röst per medlem'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))
    else:
        vote.klotter_id=klotter_id
        KlotterVote.save(vote)
        messages.add_message(request, messages.SUCCESS, _(u'Röst sparad'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))

@login_required
def comment(request, klotter_id):
    klotter = KlotterPost()
    if not get_user(request).grad.isGuest():
        klotter.writer = get_user(request).get_full_name
    form = KlotterForm(instance=klotter)
    context =  {'form' :form,'klotter_id':klotter_id}
    return render(request, 'klotter/writeComment.html', context)

@login_required
def new(request):
    return comment(request, None)

@login_required
def edit(request, klotter_id):
    klotter=KlotterPost.objects.get(pk=klotter_id)
    if klotter.member_id != get_user(request).id:
        messages.add_message(request, messages.ERROR, _(u'Du kan inte redigera andras inlägg'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))

    if request.method == 'POST':
        form = KlotterForm(request.POST, instance=klotter)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, _(u'Inlägg redigerat'))
        else:
            messages.add_message(request, messages.ERROR, _(u'Kunde inte spara inlägg. Kolla att alla obligatoriska fält är ifyllda'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))

    else:

        form = KlotterForm(instance=klotter)
    context =  {'form' :form,'klotter_id':klotter_id}
    return render(request, 'klotter/editComment.html', context)

DNM/apps/news/views.py
# coding=utf-8
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib import messages
from django.contrib.auth import get_user
from DNM.apps.news.models import News

from DNM.apps.news.forms import NewsForm
from django.utils.translation import ugettext as _

@login_required
@user_passes_test(lambda u: u.title and u.title.styrelsePost or u.is_superuser )
def edit(request, news_id):
    if news_id == u'None':
        news = News()
        form = NewsForm(instance=news)
        form = NewsForm()
    else:
        news = News.objects.get(pk=news_id)
        form = NewsForm(instance=news)
    return render_to_response('news/edit.html', {'form': form, 'news': news}, RequestContext(request))

@login_required
def view(request, news_id):
    news = News.objects.get(pk=news_id)
    return render_to_response('news/view.html', { 'news': news}, RequestContext(request))

@login_required
@user_passes_test(lambda u: u.title and u.title.styrelsePost or u.is_superuser )
def save(request, news_id):
    if request.method == 'POST':
        if news_id == u'None':
            form = NewsForm(request.POST)
        else:
            news = News.objects.get(pk=news_id)
            form = NewsForm(request.POST, instance=news)
        if form.is_valid():
            news = form.save(commit=False)
            news.member=get_user(request)
            news.save()
            messages.add_message(request, messages.SUCCESS, _('Nyhet sparad'))
            return render_to_response('news/view.html', {'news': news}, RequestContext(request))
    else:
        form = NewsForm
    news=News()
    c = {'form': form,'news': news}
    messages.add_message(request, messages.ERROR, _(u'Åtgärden misslyckades'))
    return render_to_response('news/edit.html', c, RequestContext(request))


@login_required
@user_passes_test(lambda u: u.title or u.is_superuser )
def delete(request, news_id):
    news = News.objects.get(pk=news_id)
    News.delete(news)
    messages.add_message(request, messages.SUCCESS, _('Nyhet borttagen'))
    return HttpResponseRedirect(reverse('base'))

DNM/templates/gallery/album_edit.html
{% extends "base.html" %}
{% load url from future %}
{% load widget_tweaks %}
{% load thumbnail %}
{% load i18n %}
{% block title %}{% trans "Album"%}{% endblock %}
{% block content %}
    <form action="{% url 'gallery:album_edit' album.id %}" method="post">{% csrf_token %}
        {% for field in form %}
            <div class="form-group {% if field.errors %} has-error {% endif %}">
                <label>{{ field.label }}{% if field.field.required %} * {% endif %}{{ field.errors }}</label>
                {% if field|widget_type == 'summernotewidget' %}
                    {{ field }}{{ field.errors }}
                {% else %}
                    {{ field|add_class:"form-control" }}{{ field.errors }}
                {% endif %}
            </div>
        {% endfor %}
        <input class="btn btn-success" type="submit" value="{% trans "Spara"%}"/>
<h3>{% trans "Välj pärmbild"%}</h3>
        {% for photo in album.photo_set.all %}
                <a href="{% url 'gallery:set_cover_photo'  album.id photo.id %}" style="display: inline-block">
                    {% thumbnail photo.file.url "100x100" crop="center" as im %}

                        <img class="thumbnail {% if photo.id == album.cover_photo.id %}
                                    cover-photo
                                {% endif %}" src="{{ im.url }}" width="{{ im.width }}"
                             height="{{ im.height }}">
                    {% endthumbnail %}
                </a>

        {% endfor %}
    </form>
{% endblock %}

DNM/templates/gallery/album_list.html
{% extends "base.html" %}
{% load url from future %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{% trans "Bildgalleri"%}{% endblock %}
{% block content %}
    {% load thumbnail %}

    <h1>{% trans "Album"%}<a class="btn btn-success pull-right" href={% url 'gallery:album_create' %}>{% trans "Lägg till album"%} </a></h1>

    {% for album in object_list reversed%}
        <a href="{% url 'gallery:photo_list' album.id %}">
            <h2>{{ album.title }}</h2>
            {% if album.cover_photo %}
                {% thumbnail album.cover_photo.file.url "100x100" crop="center" as im %}
                    <img class="thumbnail" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
            {% endif %}

        </a>
    {% empty %}
        {% trans "Inga album ännu"%}
    {% endfor %}


{% endblock %}

DNM/templates/gallery/album_new.html
{% extends "base.html" %}
{% load i18n %}

{% load url from future %}
{% load widget_tweaks %}
{% block title %}{% trans "Album"%}{% endblock %}
{% block content %}
 <form action="{% url 'gallery:album_create' %}" method="post">{% csrf_token %}
     {% for field in form %}
            <div class="form-group {% if field.errors %} has-error {% endif %}">
                <label>{{ field.label }}{% if field.field.required %} * {% endif %}{{ field.errors }}</label>
                {% if field|widget_type == 'summernotewidget' %}
                    {{ field }}{{ field.errors }}
                {% else %}
                    {{ field|add_class:"form-control" }}{{ field.errors }}
                {% endif %}
            </div>
        {% endfor %}
    <input class="btn btn-success" type="submit" value="{% trans "Spara"%}" />
</form>
{% endblock %}

DNM/templates/gallery/photo_list.html
{% extends "base.html" %}
{% load url from future %}
{% load widget_tweaks %}
{% load thumbnail %}
{% load i18n %}
{% block title %}{{ album.title }}{% endblock %}
{% block content %}
    <!-- templates/gallery/photo_list.html -->

    <div class="row col-lg-12">
        <h2 class="page-header">{{ album.title }} <a class="btn btn-default pull-right"
                                                     href={% url 'gallery:album_edit' album.id %}>{% trans "Ändra album"%}</a></h2>


        {% if album.description %}{{ album.description|safe }}{% endif %}
        <div class="photo-gallery">
            <ul id="gallery">
                {% for photo in object_list %}
                    <li class="loaded">
                        <a href="{{ photo.file.url }}">
                            {% thumbnail photo.file.url "100x100" crop="center" as im %}

                                <img class="thumbnail {%  if photo.id == album.cover_photo.id%}
                                    cover-photo
                                {% endif %}" src="{{ im.url }}" width="{{ im.width }}"
                                     height="{{ im.height }}">
                            {% endthumbnail %}</a>

                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="row col-lg-12">
        <h2 class="page-header">{% trans "Ladda upp bilder"%}</h2>

        <p class="text-danger">{% trans "Vänligen skala ned bilderna till < 1MB/bild."%}</p>

        <form id="add-photos" action="{% url 'gallery:ajax_photo_upload_view' album.id %}" class="dropzone">
            {% csrf_token %}
        </form>
    </div>
    <script>
        $('#gallery').photobox('a');
        // or with a fancier selector and some settings, and a callback:
        {#        $('#gallery').photobox('a', { thumbs:true, time:0 }, imageLoaded);#}
        {#        function imageLoaded(){#}
        {#            console.log('image has been loaded...');#}
        {#        }#}
    </script>

{% endblock %}