DNM/apps/gallery/urls.py
# gallery/urls.py

from django.conf.urls import patterns, url

from DNM.apps.gallery import views


urlpatterns = patterns('',
    url(
        regex=r'^(?P<pk>\d+)/ajax-upload/$',
        view=views.AjaxPhotoUploadView.as_view(),
        name='ajax_photo_upload_view',
    ),
    url(r'^album_list/$', views.AlbumListView.as_view(), name='album_list'),
    url(r'^photolist/(?P<id>\d+)$', views.PhotoListView.as_view(), name='photo_list'),

    url(r'^album_add/$', views.AlbumCreate.as_view(), name='album_create'),
    url(r'^album_edit/(?P<pk>\d+)$', views.AlbumEdit.as_view(), name='album_edit'),
    url(r'^set_cover_photo/(?P<album_id>\d+)/(?P<photo_id>\d+)$', views.set_cover_photo, name='set_cover_photo'),

    )

DNM/apps/news/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from DNM.apps.news import views


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^(?P<news_id>|None|\d+)/edit$', views.edit, name='edit'),
                       url(r'^(?P<news_id>\d+)/$', views.view, name='view'),
                       url(r'^(?P<news_id>|None|\d+)/delete$', views.delete, name='delete'),
                       url(r'^(?P<news_id>|None|\d+)/save/$', views.save, name='save')
)

DNM/apps/signup/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from DNM.apps.signup.views import *


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^(?P<event_id>|None|\d+)/signup/$', Save, name='save'),
                       url(r'^(?P<signup_id>|None|\d+)/edit/$', Edit, name='edit'),
                       url(r'^(?P<signup_id>|None|\d+)/(?P<event_id>|None|\d+)/remove/$', Remove, name='remove')
)

DNM/urls.py
from django.conf.urls import patterns, include, url

from DNM import views
from DNM.apps.news.events.views import export
from DNM.apps.static_pages.forms import editpage
from DNM.apps.static_pages.views import page
import settings




# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()
from DNM.settings import MEDIA_ROOT

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'DNM.views.home', name='home'),
                       # url(r'^DNM/', include('DNM.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       url(r'^statistics/', views.statistics, name="statistics"),
                       url(r'^contact/', views.contact, name="contact"),
                       url(r'^editpage/(?P<page_id>\w+)$', editpage, name="editpage"),

                       url(r'^page/(?P<page_id>\w+)$', page, name="page"),

                       url(r'^news/', include('DNM.apps.news.urls', namespace='news')),
                       url(r'^gallery/', include('DNM.apps.gallery.urls', namespace='gallery')),

                       url(r'^event/', include('DNM.apps.news.events.urls', namespace='event')),
                       url(r'^UserInformation/', include('DNM.apps.members.urls', namespace='UserInformation')),
                       url(r'^signup/', include('DNM.apps.signup.urls', namespace='signup')),
                       url(r'^klotterplanket/', include('DNM.apps.klotter.urls', namespace='klotter')),


                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
                       url(r'^logout/$', views.logout_, name="logout"),

                       url(r'^$', views.base, name="base"),


                       # (r'^admin/(.*)', admin.site.root),


                       url(r'^event/export/', export, name="event_ics_export"),


                       url(r'^user/password/reset/$',
                           'django.contrib.auth.views.password_reset',
                           {'post_reset_redirect': '/user/password/reset/done/'},
                           name="password_reset"),
                       (r'^user/password/reset/done/$',
                        'django.contrib.auth.views.password_reset_done'),
                       (r'^user/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                        'django.contrib.auth.views.password_reset_confirm',
                        {'post_reset_redirect': '/user/password/done/'}),
                       (r'^user/password/done/$',
                        'django.contrib.auth.views.password_reset_complete'),
                       (r'^summernote/', include('django_summernote.urls')),
                        url(r'^changeLanguage/(?P<language_code>\w+)', views.changeLanguage ,name="changeLanguage"),

)
if settings.DEBUG:
    urlpatterns += patterns(
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': MEDIA_ROOT, 'show_indexes': True}), )

DNM/apps/templatetags/models.py
__author__ = 'eaura'

DNM/apps/gallery/forms.py
from django import forms
from django.core.exceptions import ValidationError

from DNM.apps.gallery.models import Album


class AlbumForm(forms.ModelForm):



    class Meta:
        fields = ['title','description']
        model = Album

DNM/apps/klotter/forms.py
from django.forms import ModelForm
from DNM.apps.klotter.models import KlotterPost
from django_summernote.widgets import SummernoteWidget
__author__ = 'eaura'


class KlotterForm(ModelForm):
    class Meta:
        exclude = ('member','parent')
        model = KlotterPost
        widgets = {
            'text': SummernoteWidget(attrs={ 'width': '100%'}),
        }

DNM/apps/members/forms.py
# coding=utf-8

from django.forms import ModelForm, CharField, PasswordInput, Select, Textarea,DateInput,DateField
from DNM.apps.overrides.widgets import InlineCheckboxSelectMultiple
from DNM.apps.members.models import *
from widgets import AdvancedFileInput
from django.forms.models import inlineformset_factory
__author__ = 'eaura'
from functools import partial
DateInput = partial(DateInput, {'class': 'datepicker'})

class MemberForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super(MemberForm, self).__init__(*args, **kwargs)
        if self.instance.id:
            self.fields['username'].widget.attrs['readonly'] = True

            self.fields.update({
            'newPass': CharField(widget=PasswordInput(),required=False),
                 })
            self.fields['password'].label = u"Lösenord för att bekräfta ändringar"
            self.fields['newPass'].label = "Nytt password"


    class Meta:
        model = Member
        fields = (
        'username', 'first_name', 'last_name','stamma' ,'email' , 'grad', 'diet','phone', 'address','password')

        widgets = {
            'password': PasswordInput(),
            'grad': Select(),
            'address': Textarea(attrs={'cols': 80, 'rows': 5}),
            'die': Textarea(attrs={'cols': 80, 'rows': 3}),
            'stamma': Select()
        }

class MemberFormMedlem(ModelForm):

    class Meta:
        model = Member
        fields = ('grad','title','stamma')

        widgets = {
            'grad': Select(),
            'title': Select(),
            'stamma': Select(),
        }

class MemberFormKontakt(ModelForm):
    birthday = DateField(input_formats=('%d.%m.%Y',),widget=DateInput(format="%d.%m.%Y"))
    def __init__(self, *args, **kwargs):
        super(MemberFormKontakt, self).__init__(*args, **kwargs)
        if self.instance.id:
            self.fields['username'].widget.attrs['readonly'] = True

            self.fields.update({
            'newPass': CharField(widget=PasswordInput(),required=False),
                 })
            self.fields['password'].label = u"Lösenord för att bekräfta ändringar"
            self.fields['newPass'].label = "Nytt password"


    class Meta:
        model = Member
        fields = (
        'username', 'first_name', 'last_name', 'birthday','email' ,'phone', 'address','password')

        widgets = {
            'password': PasswordInput(),
            'address': Textarea(attrs={'cols': 80, 'rows': 5}),
        }



class MemberFormOther(ModelForm):

    class Meta:
        model = Member
        fields = ('diet',)

class MemberFormSuper(ModelForm):
    class Meta:
        model = Member
        fields = ('title', 'grad' )
        widgets = {
            'title': Select(),
            'grad': Select()
        }

class AvecForm(ModelForm):

    class Meta:
        model = Avec
        fields = ('name','email','diet')

DNM/apps/gallery/views.py
# gallery/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from django.views.generic import View, ListView
from django.views.generic.edit import CreateView,UpdateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone

from braces.views import (
    AjaxResponseMixin,
    JSONResponseMixin,
    LoginRequiredMixin,
    SuperuserRequiredMixin,
)

from DNM.apps.gallery.models import Album, Photo
from DNM.apps.gallery.forms import AlbumForm
from django.utils.translation import ugettext as _
class AlbumCreate(CreateView):
    form_class = AlbumForm
    success_url = '/gallery/album_list/'
    template_name = 'gallery/album_new.html'


class AlbumEdit(UpdateView):
    form_class = AlbumForm
    success_url = '/gallery/album_list/'
    template_name = 'gallery/album_edit.html'
    def get_queryset(self,**kwargs):
           # query_set = super(ModelxUpdateView, self).get_queryset().filter(user=self.request.user)
           query_set = Album.objects.filter(pk=self.kwargs['pk'])
           return query_set

class AlbumListView(ListView):

    model = Album

    def get_context_data(self, **kwargs):
        context = super(AlbumListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class PhotoListView(ListView):

    model = Photo


    def get_queryset(self, **kwargs):
        return Photo.objects.filter(album=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        context = super(PhotoListView, self).get_context_data(**kwargs)
        album = Album.objects.get(pk=self.kwargs['id'])
        context['album'] = album
        context['now'] = timezone.now()
        return context

class AjaxPhotoUploadView(LoginRequiredMixin,
                    SuperuserRequiredMixin,
                    JSONResponseMixin,
                    AjaxResponseMixin,
                    View):
    """
    View for uploading photos via AJAX.
    """
    def post_ajax(self, request, *args, **kwargs):
        try:
            album = Album.objects.get(pk=kwargs.get('pk'))
        except Album.DoesNotExist:
            error_dict = {'message': _('Fann inte albumet.')}
            return self.render_json_response(error_dict, status=404)

        uploaded_file = request.FILES['file']
        photo = Photo.objects.create(album=album, file=uploaded_file)
        photo.save()
        response_dict = {
            'message': _('Filen laddades upp!'),
        }

        return self.render_json_response(response_dict, status=200)


def set_cover_photo(request, album_id,photo_id):
    album =Album.objects.get(pk=album_id)
    album.cover_photo=Photo.objects.get(pk=photo_id)
    album.save()

    return HttpResponseRedirect(reverse('gallery:album_edit', args=(album_id)))

DNM/apps/klotter/views.py
# coding=utf-8
# -*- coding: utf-8 -*-
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from endless_pagination.decorators import page_template

from DNM.apps.klotter.forms import KlotterForm
from DNM.apps.klotter.models import KlotterPost, KlotterVote
from django.utils.translation import ugettext as _

__author__ = 'eaura'


@login_required
@page_template('klotter/klotter_page.html')  # just add this decorator
def klotterplanket(request,template='klotter.html', extra_context=None):

    if request.method == 'POST':
        form = KlotterForm(request.POST, instance=KlotterPost())
        if form.is_valid():
            klotter = form.save(commit=False)
            klotter.member = get_user(request)
            if request.POST.get("parent")!=u'None':
                parent = KlotterPost.objects.get(pk=request.POST.get("parent"))
                klotter.parent = parent
            messages.add_message(request, messages.SUCCESS, _('Kommentar sparad'))
            klotter.save()
        else:
            messages.add_message(request, messages.ERROR, _(u'Kunde inte spara inlägg. Kolla att alla obligatoriska fält är ifyllda'))

    klotter_list = [node.get_descendants(include_self=True)
         for node in KlotterPost.objects.filter(level__lte=0)]
    klotter = KlotterPost()
    if not get_user(request).grad.isGuest():
        klotter.writer = get_user(request).get_full_name
    form = KlotterForm(instance=klotter)

    context = {'nodes': klotter_list, 'form': form}
    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


@login_required
def vote(request, klotter_id):
    klotter = KlotterPost.objects.get(pk=klotter_id)
    vote, created =  KlotterVote.objects.get_or_create(member = request.user, klotter = klotter)
    if not created:
        messages.add_message(request, messages.ERROR, _(u'En röst per medlem'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))
    else:
        vote.klotter_id=klotter_id
        KlotterVote.save(vote)
        messages.add_message(request, messages.SUCCESS, _(u'Röst sparad'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))

@login_required
def comment(request, klotter_id):
    klotter = KlotterPost()
    if not get_user(request).grad.isGuest():
        klotter.writer = get_user(request).get_full_name
    form = KlotterForm(instance=klotter)
    context =  {'form' :form,'klotter_id':klotter_id}
    return render(request, 'klotter/writeComment.html', context)

@login_required
def new(request):
    return comment(request, None)

@login_required
def edit(request, klotter_id):
    klotter=KlotterPost.objects.get(pk=klotter_id)
    if klotter.member_id != get_user(request).id:
        messages.add_message(request, messages.ERROR, _(u'Du kan inte redigera andras inlägg'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))

    if request.method == 'POST':
        form = KlotterForm(request.POST, instance=klotter)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, _(u'Inlägg redigerat'))
        else:
            messages.add_message(request, messages.ERROR, _(u'Kunde inte spara inlägg. Kolla att alla obligatoriska fält är ifyllda'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))

    else:

        form = KlotterForm(instance=klotter)
    context =  {'form' :form,'klotter_id':klotter_id}
    return render(request, 'klotter/editComment.html', context)

DNM/apps/news/views.py
# coding=utf-8
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib import messages
from django.contrib.auth import get_user
from DNM.apps.news.models import News

from DNM.apps.news.forms import NewsForm
from django.utils.translation import ugettext as _

@login_required
@user_passes_test(lambda u: u.title and u.title.styrelsePost or u.is_superuser )
def edit(request, news_id):
    if news_id == u'None':
        news = News()
        form = NewsForm(instance=news)
        form = NewsForm()
    else:
        news = News.objects.get(pk=news_id)
        form = NewsForm(instance=news)
    return render_to_response('news/edit.html', {'form': form, 'news': news}, RequestContext(request))

@login_required
def view(request, news_id):
    news = News.objects.get(pk=news_id)
    return render_to_response('news/view.html', { 'news': news}, RequestContext(request))

@login_required
@user_passes_test(lambda u: u.title and u.title.styrelsePost or u.is_superuser )
def save(request, news_id):
    if request.method == 'POST':
        if news_id == u'None':
            form = NewsForm(request.POST)
        else:
            news = News.objects.get(pk=news_id)
            form = NewsForm(request.POST, instance=news)
        if form.is_valid():
            news = form.save(commit=False)
            news.member=get_user(request)
            news.save()
            messages.add_message(request, messages.SUCCESS, _('Nyhet sparad'))
            return render_to_response('news/view.html', {'news': news}, RequestContext(request))
    else:
        form = NewsForm
    news=News()
    c = {'form': form,'news': news}
    messages.add_message(request, messages.ERROR, _(u'Åtgärden misslyckades'))
    return render_to_response('news/edit.html', c, RequestContext(request))


@login_required
@user_passes_test(lambda u: u.title or u.is_superuser )
def delete(request, news_id):
    news = News.objects.get(pk=news_id)
    News.delete(news)
    messages.add_message(request, messages.SUCCESS, _('Nyhet borttagen'))
    return HttpResponseRedirect(reverse('base'))

DNM/templates/events/all.html
{% extends "base.html" %}
{% load i18n %}
{% load url from future %}


{% block title %}{% trans "Alla event"%}{% endblock %}
{% block content %}


    <h3>{% trans "Alla event" %}</h3>
    {% for event in event_list %}
            <div style="margin-bottom: 5px">
                <a style="display: inline-block" href={% url 'event:view' event.id %}>{{ event.name }}</a>
                <span style="display: inline-block;font-size: 10px"><b>{{ event.date|date:"d.n.Y : H:i" }}</b></span>
            </div>
    {% endfor %}

{% endblock %}

DNM/templates/events/edit.html
{% extends "base.html" %}
{% load url from future %}
{% load widget_tweaks %}
{% load i18n %}

{% block title %}{{ event.name }}{% endblock %}
{% block content %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/cloneMore.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
    <script src="{{ STATIC_URL }}js/datepicker.js"></script>
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/base/jquery-ui.css" type="text/css"
          rel="stylesheet"/>

    <h3> {{ event.name }}</h3>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form class="form-horizontal" style="margin-bottom: 10px" role="form" action="{% url 'event:save' event.id %}"
          method="post">{% csrf_token %}
        {% csrf_token %}


         {% for field in form %}
            <div class="form-group {% if field.errors %} has-error {% endif %}">
                <label>{{ field.label }}{% if field.field.required %} * {% endif %}{{ field.errors }}</label>
                {% if field|widget_type == 'summernotewidget' %}
                    {{ field }}{{ field.errors }}
                {% else %}
                    {{ field|add_class:"form-control" }}{{ field.errors }}
                {% endif %}
            </div>
        {% endfor %}
        <h4>{% trans "Extra textfält" %} </h4>

        <div id="extra_textfields_btn_div">
            <input class="btn btn-default" type="button" value="{% trans "Visa extra textfält"%}" id="extra_textfields_btn">
        </div>


        <div id="extra_textfields" style="display: none">


            {{ textfieldFormSet.management_form }}
            <hr>
            {% for textfieldForm in textfieldFormSet %}
                <div class='textfield' id="textfield_{{ forloop.counter }}">
                    {% for field in textfieldForm.visible_fields %}
                        <div class="form-group  {% if field.errors %} has-error {% endif %} ">
                            <label for="id_textFields-{{ forloop.parentloop.counter0 }}-{{ field.name }}"
                                   class="col-xs-2 control-label">{{ field.label }}</label>

                            <div class="col-xs-10">
                                {{ field|add_class:"form-control" }}{{ field.errors }}
                            </div>
                        </div>

                    {% endfor %}
                    <hr>
                    {% for field in textfieldForm.hidden_fields %}
                        {{ field|add_class:"form-control"|attr:"visibility:hidden" }}
                    {% endfor %}
                </div>
            {% endfor %}
            <input class="btn btn-default" type="button" value="{% trans "Lägg till textfält"%}" id="add_textfield">
        </div>

        <h4>{% trans "Extra checkboxar" %}</h4>

        <div id="extra_checkboxes_btn_div">
            <input class="btn btn-default" type="button" value="{% trans "Visa extra checkboxar"%}" id="extra_checkboxes_btn">
        </div>

        <div id="extra_checkboxes" style="display: none">
            {{ checkboxFormSet.management_form }}

            <hr>
            {% for checkboxForm in checkboxFormSet %}
                <div class="checkbox_" id="checkbox_{{ forloop.counter }}">
                    {% for field in checkboxForm.visible_fields %}
                        <div class="form-group  {% if field.errors %} has-error {% endif %} ">
                            <label for="id_checkboxes-{{ forloop.parentloop.counter0 }}-{{ field.name }}"
                                   class="col-xs-2 control-label">{{ field.label }}</label>

                            <div class="col-xs-10">
                                {{ field|add_class:"form-control" }}{{ field.errors }}
                            </div>
                        </div>
                    {% endfor %}
                    <hr>
                    {% for field in checkboxForm.hidden_fields %}
                        {{ field|add_class:"form-control"|attr:"visibility:hidden" }}
                    {% endfor %}
                </div>

            {% endfor %}
            <input class="btn btn-default" type="button" value="{% trans "Lägg till checkbox"%}" id="add_checkbox">

        </div>
        <br/>


        <input class="btn btn-default" type="submit" value="{% trans "Spara"%}"/>
    </form>


{% endblock %}
 {% block scripts %}
 <script>
     $(document).ready(function () {
            $('.datepicker').datetimepicker({dateFormat: 'dd.mm.yy'});
        });
        {#        Clone textfield functionality#}
        $('#add_textfield').click(function () {
            cloneMore('div.textfield:last', 'textFields');
        });

        {#        Show extra textfields#}
        $('#extra_textfields_btn').click(function () {
            $("#extra_textfields").show();
            $("#extra_textfields_btn_div").hide();
        });

        {#        Show extra textfields if first textfields is not empty#}
        if ($('#textfield_1 input').val() != '') {
            $("#extra_textfields").show();
            $("#extra_textfields_btn_div").hide();
        } else {
            $("#extra_textfields").hide();
            $("#extra_textfields_btn_div").show();
        }

        {#      Clone checkbox functionality#}
        $('#add_checkbox').click(function () {
            cloneMore('div.checkbox_:last', 'checkboxes');
        });

        {#        show extra checkboxes#}
        $('#extra_checkboxes_btn').click(function () {
            $("#extra_checkboxes").show();
            $("#extra_checkboxes_btn_div").hide();
        });

        {#        Show extra checkoboxes if first is not emptyF#}
        if ($('#checkbox_1 input').val() != '') {
            $("#extra_checkboxes").show();
            $("#extra_checkboxes_btn_div").hide();
        } else {
            $("#extra_checkboxes").hide();
            $("#extra_checkboxes_btn_div").show();
        }

        jQuery.each($("select[multiple]"), function () {
            // "Locations" can be any label you want
            SelectFilter.init(this.id, "grader", 0, "/media/");
        });
    </script>
{% endblock %}

DNM/templates/events/events.html
{% load url from future %}
{% load i18n %}

<script type="text/javascript">
    var myCal = new JEC('calendar', {
        tableClass: 'greyCalendar panel panel-default',
        firstMonth: 201301,
        lastMonth: 203010,
        firstDayOfWeek: 2,
        specialDays: [ 1 ],
        linkNewWindow: false,
        months: ["{% trans "Jan"%}", "{% trans "Feb"%}", "{% trans "Mar"%}", "{% trans "Apr"%}", "{% trans "Maj"%}", "{% trans "Jun"%}", "{% trans "Jul"%}", "{% trans "Aug"%}", "{% trans "Sep"%}", "{% trans "Okt"%}", "{% trans "Nov"%}", "{% trans "Dec"%}"],
        weekdays: [
            "S",
            "M",
            "T",
            "O",
            "T",
            "F",
            "L"
            ]
    });

    myCal.defineEvents(
            [
                {% for event in event_list %}
                    {
                        eventDate: {{ event.getCalendarDate}},
                        eventDescription: '{{ event.name}}',
                        eventLink:'{% url 'event:view' event.id %}',
                        eventType :'{{ event.madeByAdmin}}'
                    },
                {% endfor %}
                {
                    eventDate: '20130101',
                    eventDescription: '',
                    eventLink: ''
                }
            ]
    );

    myCal.showCalendar()

</script>

    {% for event in event_list %}
        <div style="margin-bottom: 5px">
            <a href={% url 'event:view' event.id %}>{{ event.name }}</a><br>
            <div style="font-size: 10px"><b>{{ event.date|date:"d.n.Y : H:i" }}</b> | <i>{% trans "Anmälan stänger"%}: {{ event.deadline|date:"d.n : H:i" }}</i></div>
        </div>
    {% endfor %}
<div id="calendar">

</div>
<a href={% url 'event_ics_export' %}> <img src="/static/images/event_feed.png" alt="iCal feed"/></a>