DNM/apps/gallery/urls.py
# gallery/urls.py

from django.conf.urls import patterns, url

from DNM.apps.gallery import views


urlpatterns = patterns('',
    url(
        regex=r'^(?P<pk>\d+)/ajax-upload/$',
        view=views.AjaxPhotoUploadView.as_view(),
        name='ajax_photo_upload_view',
    ),
    url(r'^album_list/$', views.AlbumListView.as_view(), name='album_list'),
    url(r'^photolist/(?P<id>\d+)$', views.PhotoListView.as_view(), name='photo_list'),

    url(r'^album_add/$', views.AlbumCreate.as_view(), name='album_create'),
    url(r'^album_edit/(?P<pk>\d+)$', views.AlbumEdit.as_view(), name='album_edit'),
    url(r'^set_cover_photo/(?P<album_id>\d+)/(?P<photo_id>\d+)$', views.set_cover_photo, name='set_cover_photo'),

    )

DNM/apps/members/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from DNM.apps.members import views


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^$', views.users, name='users'),
                       url(r'^(?P<user_id>\w+)$', views.profile, name='profile'),
                       url(r'^save/(?P<user_id>\w+)$', views.save, name='save'),
                       url(r'^adminSave/(?P<user_id>\w+)$', views.adminSave, name='adminSave'),
                       url(r'^delete/(?P<user_id>\w+)$', views.delete, name='delete'),
                       url(r'^admin/(?P<user_id>\w+)$', views.admin, name='admin'),
                       url(r'^kontakt/(?P<user_id>\w+)$', views.kontakt, name='kontakt'),
                       url(r'^medlem/(?P<user_id>\w+)$', views.medlem, name='medlem'),
                       url(r'^other/(?P<user_id>\w+)$', views.other, name='other'),
                       url(r'^new/$', views.new, name='new'),


                       )

DNM/apps/news/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from DNM.apps.news import views


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^(?P<news_id>|None|\d+)/edit$', views.edit, name='edit'),
                       url(r'^(?P<news_id>\d+)/$', views.view, name='view'),
                       url(r'^(?P<news_id>|None|\d+)/delete$', views.delete, name='delete'),
                       url(r'^(?P<news_id>|None|\d+)/save/$', views.save, name='save')
)

DNM/apps/signup/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from DNM.apps.signup.views import *


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^(?P<event_id>|None|\d+)/signup/$', Save, name='save'),
                       url(r'^(?P<signup_id>|None|\d+)/edit/$', Edit, name='edit'),
                       url(r'^(?P<signup_id>|None|\d+)/(?P<event_id>|None|\d+)/remove/$', Remove, name='remove')
)

DNM/urls.py
from django.conf.urls import patterns, include, url

from DNM import views
from DNM.apps.news.events.views import export
from DNM.apps.static_pages.forms import editpage
from DNM.apps.static_pages.views import page
import settings




# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()
from DNM.settings import MEDIA_ROOT

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'DNM.views.home', name='home'),
                       # url(r'^DNM/', include('DNM.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       url(r'^statistics/', views.statistics, name="statistics"),
                       url(r'^contact/', views.contact, name="contact"),
                       url(r'^editpage/(?P<page_id>\w+)$', editpage, name="editpage"),

                       url(r'^page/(?P<page_id>\w+)$', page, name="page"),

                       url(r'^news/', include('DNM.apps.news.urls', namespace='news')),
                       url(r'^gallery/', include('DNM.apps.gallery.urls', namespace='gallery')),

                       url(r'^event/', include('DNM.apps.news.events.urls', namespace='event')),
                       url(r'^UserInformation/', include('DNM.apps.members.urls', namespace='UserInformation')),
                       url(r'^signup/', include('DNM.apps.signup.urls', namespace='signup')),
                       url(r'^klotterplanket/', include('DNM.apps.klotter.urls', namespace='klotter')),


                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
                       url(r'^logout/$', views.logout_, name="logout"),

                       url(r'^$', views.base, name="base"),


                       # (r'^admin/(.*)', admin.site.root),


                       url(r'^event/export/', export, name="event_ics_export"),


                       url(r'^user/password/reset/$',
                           'django.contrib.auth.views.password_reset',
                           {'post_reset_redirect': '/user/password/reset/done/'},
                           name="password_reset"),
                       (r'^user/password/reset/done/$',
                        'django.contrib.auth.views.password_reset_done'),
                       (r'^user/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                        'django.contrib.auth.views.password_reset_confirm',
                        {'post_reset_redirect': '/user/password/done/'}),
                       (r'^user/password/done/$',
                        'django.contrib.auth.views.password_reset_complete'),
                       (r'^summernote/', include('django_summernote.urls')),
                        url(r'^changeLanguage/(?P<language_code>\w+)', views.changeLanguage ,name="changeLanguage"),

)
if settings.DEBUG:
    urlpatterns += patterns(
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': MEDIA_ROOT, 'show_indexes': True}), )

DNM/apps/members/models.py
# coding=utf-8
from django.utils.translation import ugettext as _
from sorl.thumbnail import ImageField

from django.contrib.auth.models import *
from django.db import models
from django.contrib.auth import models as auth_models
import os

__author__ = 'eaura'

class Grad(models.Model):
    def __unicode__(self):
        return self.grad

    grad = models.CharField(max_length=200, verbose_name=_('Noblett'))
    order = models.SmallIntegerField(verbose_name=_('Ordning'))

    def isGuest(self):
        if self.grad == u'Gäst':
            return True
        else:
            return False

    class Meta:
        ordering = ('order',)

class Stamma(models.Model):
    def __unicode__(self):
        return self.namn or u''
    namn = models.NullBooleanField(max_length=200, verbose_name=_(u'Stämma'))

    namn = models.CharField(max_length=200, verbose_name=_(u'Titel'))
class Title(models.Model):
    def __unicode__(self):
        return self.namn or u''
    styrelsePost = models.NullBooleanField(max_length=200, verbose_name=_(u'Styrelsepost'))

    namn = models.CharField(max_length=200, verbose_name=_(u'Titel'))

class MyUserManager(BaseUserManager):
    def create_user(self, username, email=None, password=None, **extra_fields):
        now = timezone.now()
        if not email:
            raise ValueError(_('The given email must be set'))
        email = UserManager.normalize_email(email)
        user = self.model(username=username, email=email,
                          is_staff=False, is_active=True, is_superuser=False,
                          last_login=now, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password, **extra_fields):
        u = self.create_user(username, email, password, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.is_superuser = True
        u.save(using=self._db)
        return u

def get_image_path(instance, filename):
    return os.path.join('photos', str(instance.id), filename)

class Member(AbstractBaseUser, PermissionsMixin):
    # Link to the user model
    username = models.CharField(max_length=30, unique=True, db_index=True, verbose_name=_(u'Användarnamn'))
    email = models.EmailField('E-post', max_length=254, unique=True)
    first_name = models.CharField(max_length=200, verbose_name=_(u'Förnamn'))
    last_name = models.CharField(max_length=200, verbose_name=_('Efternamn'))
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']
    # fodelsedatum = models.DateField('date of birth', blank=True, null=True)
    grad = models.ForeignKey(Grad, blank=False, default=1)
    title = models.ForeignKey(Title, blank=True, null=True, verbose_name=_(u'Titel'))
    stamma = models.ForeignKey(Stamma, blank=True, null=True, verbose_name=(u'Stämma'))
    date_joined = models.DateTimeField('date joined', default=timezone.now)
    phone = models.CharField(max_length=200, blank=True, verbose_name=_(u'Telefonnummer'))
    address = models.CharField(max_length=200, blank=True, verbose_name=_(u'Postadress'))
    is_staff = models.BooleanField('staff status', default=False,
                                   help_text='Designates whether the user can log into this admin '
                                             'site.')
    is_active = models.BooleanField('active', default=True,
                                    help_text='Designates whether this user should be treated as '
                                              'active. Unselect this instead of deleting accounts.')

    image = ImageField(upload_to=get_image_path, blank=True, null=True,  verbose_name=_(u'Profilbild'))
    diet  = models.CharField(max_length=500, blank=True, null=True, verbose_name=_(u'Diet'))
    birthday = models.DateTimeField(verbose_name=_(u'Födelsetid'),blank=False,null=True)


    def up_to_date(self):
        return self.birthday is not None

    def get_full_name(self):
        full_name = ''
        if self.title:
            full_name += ' '
            full_name += self.title.namn
        if self.grad:
            full_name += ' '
            full_name += self.grad.grad
        full_name += ' '
        full_name +=self.first_name +" "+self.last_name
        return full_name

    def get_short_name(self):
        return self.first_name+" " + self.last_name

    objects = MyUserManager()

auth_models.User = Member

class Avec(models.Model):
    def __unicode__(self):
        return self.name

    name = models.CharField(max_length=200, verbose_name=_(u'Namn'))
    diet = models.CharField(max_length=200, verbose_name=_(u'Diet'),null=True, blank=True)
    email = models.CharField(max_length=200, verbose_name=_(u'E-post'))
    members  = models.ForeignKey(Member, blank=True, null=True, verbose_name=_(u'Avec'))

# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_save
from django.dispatch.dispatcher import receiver

@receiver(pre_save, sender=Member)
def delete_old_image(sender, instance, *args, **kwargs):
    if instance.pk:
        existing_image = Member.objects.get(pk=instance.pk)
        if instance.image and existing_image.image != instance.image:
            existing_image.image.delete(False)

DNM/apps/gallery/forms.py
from django import forms
from django.core.exceptions import ValidationError

from DNM.apps.gallery.models import Album


class AlbumForm(forms.ModelForm):



    class Meta:
        fields = ['title','description']
        model = Album

DNM/apps/klotter/forms.py
from django.forms import ModelForm
from DNM.apps.klotter.models import KlotterPost
from django_summernote.widgets import SummernoteWidget
__author__ = 'eaura'


class KlotterForm(ModelForm):
    class Meta:
        exclude = ('member','parent')
        model = KlotterPost
        widgets = {
            'text': SummernoteWidget(attrs={ 'width': '100%'}),
        }

DNM/apps/news/forms.py
from django.forms import ModelForm
from django.db import models
from django.utils import timezone
from django import forms
from datetime import timedelta
from DNM.apps.news.models import News
from django.contrib.admin.widgets import FilteredSelectMultiple
from django_summernote.widgets import SummernoteWidget

class NewsForm(ModelForm):
    class Meta:
        exclude = ('member',)
        model = News
        widgets = {
            'description': SummernoteWidget(attrs={'width': '100%'}),
        }

DNM/apps/gallery/views.py
# gallery/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from django.views.generic import View, ListView
from django.views.generic.edit import CreateView,UpdateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone

from braces.views import (
    AjaxResponseMixin,
    JSONResponseMixin,
    LoginRequiredMixin,
    SuperuserRequiredMixin,
)

from DNM.apps.gallery.models import Album, Photo
from DNM.apps.gallery.forms import AlbumForm
from django.utils.translation import ugettext as _
class AlbumCreate(CreateView):
    form_class = AlbumForm
    success_url = '/gallery/album_list/'
    template_name = 'gallery/album_new.html'


class AlbumEdit(UpdateView):
    form_class = AlbumForm
    success_url = '/gallery/album_list/'
    template_name = 'gallery/album_edit.html'
    def get_queryset(self,**kwargs):
           # query_set = super(ModelxUpdateView, self).get_queryset().filter(user=self.request.user)
           query_set = Album.objects.filter(pk=self.kwargs['pk'])
           return query_set

class AlbumListView(ListView):

    model = Album

    def get_context_data(self, **kwargs):
        context = super(AlbumListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class PhotoListView(ListView):

    model = Photo


    def get_queryset(self, **kwargs):
        return Photo.objects.filter(album=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        context = super(PhotoListView, self).get_context_data(**kwargs)
        album = Album.objects.get(pk=self.kwargs['id'])
        context['album'] = album
        context['now'] = timezone.now()
        return context

class AjaxPhotoUploadView(LoginRequiredMixin,
                    SuperuserRequiredMixin,
                    JSONResponseMixin,
                    AjaxResponseMixin,
                    View):
    """
    View for uploading photos via AJAX.
    """
    def post_ajax(self, request, *args, **kwargs):
        try:
            album = Album.objects.get(pk=kwargs.get('pk'))
        except Album.DoesNotExist:
            error_dict = {'message': _('Fann inte albumet.')}
            return self.render_json_response(error_dict, status=404)

        uploaded_file = request.FILES['file']
        photo = Photo.objects.create(album=album, file=uploaded_file)
        photo.save()
        response_dict = {
            'message': _('Filen laddades upp!'),
        }

        return self.render_json_response(response_dict, status=200)


def set_cover_photo(request, album_id,photo_id):
    album =Album.objects.get(pk=album_id)
    album.cover_photo=Photo.objects.get(pk=photo_id)
    album.save()

    return HttpResponseRedirect(reverse('gallery:album_edit', args=(album_id)))

DNM/apps/news/views.py
# coding=utf-8
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib import messages
from django.contrib.auth import get_user
from DNM.apps.news.models import News

from DNM.apps.news.forms import NewsForm
from django.utils.translation import ugettext as _

@login_required
@user_passes_test(lambda u: u.title and u.title.styrelsePost or u.is_superuser )
def edit(request, news_id):
    if news_id == u'None':
        news = News()
        form = NewsForm(instance=news)
        form = NewsForm()
    else:
        news = News.objects.get(pk=news_id)
        form = NewsForm(instance=news)
    return render_to_response('news/edit.html', {'form': form, 'news': news}, RequestContext(request))

@login_required
def view(request, news_id):
    news = News.objects.get(pk=news_id)
    return render_to_response('news/view.html', { 'news': news}, RequestContext(request))

@login_required
@user_passes_test(lambda u: u.title and u.title.styrelsePost or u.is_superuser )
def save(request, news_id):
    if request.method == 'POST':
        if news_id == u'None':
            form = NewsForm(request.POST)
        else:
            news = News.objects.get(pk=news_id)
            form = NewsForm(request.POST, instance=news)
        if form.is_valid():
            news = form.save(commit=False)
            news.member=get_user(request)
            news.save()
            messages.add_message(request, messages.SUCCESS, _('Nyhet sparad'))
            return render_to_response('news/view.html', {'news': news}, RequestContext(request))
    else:
        form = NewsForm
    news=News()
    c = {'form': form,'news': news}
    messages.add_message(request, messages.ERROR, _(u'Åtgärden misslyckades'))
    return render_to_response('news/edit.html', c, RequestContext(request))


@login_required
@user_passes_test(lambda u: u.title or u.is_superuser )
def delete(request, news_id):
    news = News.objects.get(pk=news_id)
    News.delete(news)
    messages.add_message(request, messages.SUCCESS, _('Nyhet borttagen'))
    return HttpResponseRedirect(reverse('base'))

DNM/templates/userInformation/profile.html
{% extends "base.html" %}
{% load url from future %}
{% load i18n %}
{% load thumbnail %}
{% load widget_tweaks %}
{% load gravatar %}
{% if text %}
    {% block title %} {% trans "Användare"%}{% endblock %}
{% endif %}



{% block content %}

    <div class="row">
        <div class="col-sm-3">
            <img src="{% gravatar_url "user_.email 200" %}" class="img-thumbnail">
        </div>
        <div class="col-sm-9">
            <div class="row">
                <div class="col-sm-12">
                    <h2 class="help-block">
                        {{ user_.get_full_name }}
                    </h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <strong> {% trans "Födelsetid"%}</strong>
                </div>
                <div class="col-sm-9">
                    {{ user_.birthday|date:"d.m.Y" }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <strong> {% trans "Email"%}</strong>
                </div>
                <div class="col-sm-9">
                    {{ user_.email }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-3">
                    <strong> {% trans "Telefon"%}</strong>
                </div>
                <div class="col-sm-9">
                    {{ user_.phone }}
                </div>

            </div>
            <div class="row">
                <div class="col-sm-3">
                    <strong> {% trans "Postadress"%}</strong>
                </div>
                <div class="col-sm-9">
                    {{ user_.address }}
                </div>
            </div>
            {% if user_.id == request.user.id or user_.id == None %}
                <a class="btn btn-default" href="#" data-toggle="modal" data-target="#ajax-modal"
                   data-href="{% url 'UserInformation:kontakt' user_.id %}">
                    {% trans "Ändra personuppgifter"%}
                </a>
            {% endif %}
            {% if user.title.styrelsePost or user.is_superuser %}
                <a class="btn btn-default" href="#" data-toggle="modal" data-target="#ajax-modal"
                   data-href="{% url 'UserInformation:admin' user_.id %}">
                    {% trans "Administrera"%}
                </a>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                <div class="col-sm-12">
                    <h4>{% trans "Medlemsuppgifter"%}</h4>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-5">
                    <strong> {% trans "Stämma"%}</strong>
                </div>
                <div class="col-sm-7">
                    {{ user_.stamma.namn }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-5">
                    <strong> {% trans "Titel"%}</strong>
                </div>
                <div class="col-sm-7">
                    {{ user_.title.namn }}
                </div>
            </div>
            <div class="row">
                <div class="col-sm-5">
                    <strong> {% trans "Noblett"%}</strong>
                </div>
                <div class="col-sm-7">
                    {{ user_.grad.grad }}
                </div>
            </div>
            {% if user_.id == request.user.id or user_.id == None %}
                <a class="btn btn-default" href="#" data-toggle="modal" data-target="#ajax-modal"
                   data-href="{% url 'UserInformation:medlem' user_.id %}">
                    {% trans "Ändra medlemsuppgifter"%}
                </a>
            {% endif %}
        </div>
        {% if user_.id == request.user.id or user_.id == None %}
            <div class="col-sm-6">
                <div class="row">
                    <div class="col-sm-12">
                        <h4>{% trans "Övriga uppgifter"%}</h4>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-5">
                        <strong> {% trans "Dieter"%}</strong>
                    </div>
                    <div class="col-sm-7">
                        {{ user_.diet }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-5">
                        <strong> {% trans "Avecer"%}</strong>
                    </div>
                    <div class="col-sm-7">
                        {% for avec in user_.avec_set.all %}
                            {{ avec.name }},
                        {% endfor %}
                    </div>
                </div>

                <a class="btn btn-default" href="#" data-toggle="modal" data-target="#ajax-modal"
                   data-href="{% url 'UserInformation:other' user_.id %}">
                    {% trans "Ändra övriga uppgifter"%}
                </a>

            </div>
        {% endif %}
    </div>

    {% block scripts %}

        <script> setTimeout(function () {
            jQuery('#modal').modal('hide');
        }, 1000);
        $('body').on('hidden.bs.modal', '.modal', function () {
            $(this).removeData('bs.modal');
        }); </script> {% endblock %}

{% endblock %}

DNM/templates/userInformation/users.html
{% extends "base.html" %}
{% load url from future %}
{% load thumbnail %}
{% load gravatar %}
{% load i18n %}

{% block extrahead %}
    <script type="text/javascript" src="{{ STATIC_URL }}js/table2CSV.js"></script>
{% endblock %}
{% if text %}
    {% block title %}{% trans "Användare"%}{% endblock %}
{% endif %}



{% block content %}

    <h3>{% trans "Medlemmar"%}</h3>
    {% if users %}
        <div class="row">
        <div class="col-sm-4" id="userData">
            <a href="#" class="export btn btn-primary">{% trans "Exportera till .csv (Excel)"%}</a>
        </div>
        <div class="col-sm-8" id="userData">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search" name="srch-term" id="search">

                <div class="input-group-btn">
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                </div>
            </div>
            <br>
        </div>
        </div>
        <div class="row">
        <div class="col-sm-12" id="userData">
            <table id="user-table"  data-tablesaw-mode="swipe"
                   class=" tablesaw table table-striped table-hover table-condensed"
                   data-tablesaw-sortable data-tablesaw-minimap data-tablesaw-mode-switch>
                <thead>
                <tr>
                     <th data-tablesaw-sortable-col data-tablesaw-priority="1">
                        {% trans "Bild"%}
                    </th>
                    <th data-tablesaw-sortable-col data-tablesaw-sortable-default-col data-tablesaw-priority="persist">
                        {% trans "Namn"%}
                    </th>
                    <th data-tablesaw-sortable-col data-tablesaw-priority="2">
                        {% trans "Titel"%}
                    </th>
                    <th data-tablesaw-sortable-col data-tablesaw-priority="2">
                        {% trans "Noblett"%}
                    </th>
                    <th data-tablesaw-sortable-col data-tablesaw-priority="2">
                        {% trans "Stämma"%}
                    </th>
                    <th data-tablesaw-sortable-col data-tablesaw-priority="3">
                        {% trans "Födelsetid"%}
                    </th>
                    <th data-tablesaw-sortable-col data-tablesaw-priority="3">
                        {% trans "Telefonnummer"%}
                    </th>
                    <th data-tablesaw-sortable-col data-tablesaw-priority="3">
                        {% trans "E-post"%}
                    </th>
                    <th data-tablesaw-sortable-col data-tablesaw-priority="3">
                        {% trans "Postadress"%}
                    </th>
                    {% if user.title.styrelsePost or user.is_superuser %}
                        <th data-tablesaw-priority="1">
                            {% trans "Admin"%}
                        </th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for user_ in users %}
                    <tr>
                         <td>
                             <img src="{% gravatar_url "user_.email 26" %}" class="img-rounded">
                        </td>
                        <td>
                            <a href={% url 'UserInformation:profile' user_.id %}> {{ user_.get_short_name }}</a>
                        </td>
                        <td>
                            {{ user_.title.namn }}
                        </td>
                        <td>
                            {{ user_.grad }}
                        </td>
                        <td>
                            {{ user_.stamma }}
                        </td>
                        <td>
                            {{ user_.birthday|date:"d.m.Y" }}
                        </td>
                        <td>
                            {{ user_.phone }}

                        </td>
                        <td>
                            {{ user_.email }}

                        </td>
                        <td>
                            {{ user_.address }}

                        </td>
                        {% if user.title.styrelsePost or user.is_superuser %}
                            <td>


                                <a class="btn btn-default" href="#" data-toggle="modal" data-target="#ajax-modal"
                                   data-href="{% url 'UserInformation:admin'  user_.id %}">
                                    {% trans "Administrera"%}
                                </a>

                                <form style=" margin-bottom:0px;display:inline-block" class="form-inline"
                                      action="{% url 'UserInformation:delete' user_.id %}" method="post">
                                    {% csrf_token %}
                                    <input id="confirm" class="btn btn-danger" type="submit" value="{% trans "Ta bort"%} onclick="return confirm('{% trans "Är du säker på att du vill ta bort"%} {{ user_.get_full_name }}')"/>
                                </form>


                            </td>
                        {% endif %}

                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
     </div>
    {% else %}
        <p>{% trans "Inga användare"%}.</p>
    {% endif %}




{% endblock %}

{% block scripts %}
    <script>

        $(document).ready(function () {

            function exportTableToCSV($table, filename) {

                var $rows = $table.find('tr:has(td,th):visible'),

                // Temporary delimiter characters unlikely to be typed by keyboard
                // This is to avoid accidentally splitting the actual contents
                        tmpColDelim = String.fromCharCode(11), // vertical tab character
                        tmpRowDelim = String.fromCharCode(0), // null character

                // actual delimiter characters for CSV format
                        colDelim = '","',
                        rowDelim = '"\r\n"',

                // Grab text from table into CSV formatted string
                        csv = '"' + $rows.map(function (i, row) {
                            var $row = $(row),
                                    $cols = $row.find('td:visible, th:visible');

                            return $cols.map(function (j, col) {
                                var $col = $(col),
                                        text = $col.text();
                                text = text.trim();
                                return text.replace('"', '""'); // escape double quotes


                            }).get().join(tmpColDelim);

                        }).get().join(tmpRowDelim)
                                .split(tmpRowDelim).join(rowDelim)
                                .split(tmpColDelim).join(colDelim) + '"',

                // Data URI
                        csvData = 'data:application/csv;charset=utf-8,' + encodeURIComponent(csv);

                $(this)
                        .attr({
                            'download': filename,
                            'href': csvData,
                            'target': '_blank'
                        });
            }

            // This must be a hyperlink
            $(".export").on('click', function (event) {
                // CSV
                exportTableToCSV.apply(this, [$('#userData>table'), 'export.csv']);

                // IF CSV, don't do event.preventDefault() or return false
                // We actually need this to be a typical hyperlink
            });
        });

        $("#search").keyup(function () {
            _this = this;
            // Show only matching TR, hide rest of them
            $.each($("#user-table tbody").find("tr"), function () {
                console.log($(this).text());
                if ($(this).text().toLowerCase().indexOf($(_this).val().toLowerCase()) == -1)
                    $(this).hide();
                else
                    $(this).show();
            });
        });
    </script>


{% endblock %}