DNM/apps/gallery/urls.py
# gallery/urls.py

from django.conf.urls import patterns, url

from DNM.apps.gallery import views


urlpatterns = patterns('',
    url(
        regex=r'^(?P<pk>\d+)/ajax-upload/$',
        view=views.AjaxPhotoUploadView.as_view(),
        name='ajax_photo_upload_view',
    ),
    url(r'^album_list/$', views.AlbumListView.as_view(), name='album_list'),
    url(r'^photolist/(?P<id>\d+)$', views.PhotoListView.as_view(), name='photo_list'),

    url(r'^album_add/$', views.AlbumCreate.as_view(), name='album_create'),
    url(r'^album_edit/(?P<pk>\d+)$', views.AlbumEdit.as_view(), name='album_edit'),
    url(r'^set_cover_photo/(?P<album_id>\d+)/(?P<photo_id>\d+)$', views.set_cover_photo, name='set_cover_photo'),

    )

DNM/apps/klotter/urls.py
__author__ = 'eaura'

from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin


from DNM.apps.klotter.views import *

admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^$', klotterplanket, name="klotterplanket"),
                       url(r'^(?P<klotter_id>\d+)/$', vote, name='vote'),
                       url(r'^comment/(?P<klotter_id>\d+)/$', comment, name='comment'),
                       url(r'^new/$', new, name='new'),
                       url(r'^edit/(?P<klotter_id>\d+)/$', edit, name='edit'),
)

DNM/apps/members/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from DNM.apps.members import views


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^$', views.users, name='users'),
                       url(r'^(?P<user_id>\w+)$', views.profile, name='profile'),
                       url(r'^save/(?P<user_id>\w+)$', views.save, name='save'),
                       url(r'^adminSave/(?P<user_id>\w+)$', views.adminSave, name='adminSave'),
                       url(r'^delete/(?P<user_id>\w+)$', views.delete, name='delete'),
                       url(r'^admin/(?P<user_id>\w+)$', views.admin, name='admin'),
                       url(r'^kontakt/(?P<user_id>\w+)$', views.kontakt, name='kontakt'),
                       url(r'^medlem/(?P<user_id>\w+)$', views.medlem, name='medlem'),
                       url(r'^other/(?P<user_id>\w+)$', views.other, name='other'),
                       url(r'^new/$', views.new, name='new'),


                       )

DNM/apps/news/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from DNM.apps.news import views


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^(?P<news_id>|None|\d+)/edit$', views.edit, name='edit'),
                       url(r'^(?P<news_id>\d+)/$', views.view, name='view'),
                       url(r'^(?P<news_id>|None|\d+)/delete$', views.delete, name='delete'),
                       url(r'^(?P<news_id>|None|\d+)/save/$', views.save, name='save')
)

DNM/apps/signup/urls.py
from django.conf.urls import patterns
from django.conf.urls import url
from django.contrib import admin

from DNM.apps.signup.views import *


admin.autodiscover()
urlpatterns = patterns('',
                       url(r'^(?P<event_id>|None|\d+)/signup/$', Save, name='save'),
                       url(r'^(?P<signup_id>|None|\d+)/edit/$', Edit, name='edit'),
                       url(r'^(?P<signup_id>|None|\d+)/(?P<event_id>|None|\d+)/remove/$', Remove, name='remove')
)

DNM/urls.py
from django.conf.urls import patterns, include, url

from DNM import views
from DNM.apps.news.events.views import export
from DNM.apps.static_pages.forms import editpage
from DNM.apps.static_pages.views import page
import settings




# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()
from DNM.settings import MEDIA_ROOT

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'DNM.views.home', name='home'),
                       # url(r'^DNM/', include('DNM.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       url(r'^statistics/', views.statistics, name="statistics"),
                       url(r'^contact/', views.contact, name="contact"),
                       url(r'^editpage/(?P<page_id>\w+)$', editpage, name="editpage"),

                       url(r'^page/(?P<page_id>\w+)$', page, name="page"),

                       url(r'^news/', include('DNM.apps.news.urls', namespace='news')),
                       url(r'^gallery/', include('DNM.apps.gallery.urls', namespace='gallery')),

                       url(r'^event/', include('DNM.apps.news.events.urls', namespace='event')),
                       url(r'^UserInformation/', include('DNM.apps.members.urls', namespace='UserInformation')),
                       url(r'^signup/', include('DNM.apps.signup.urls', namespace='signup')),
                       url(r'^klotterplanket/', include('DNM.apps.klotter.urls', namespace='klotter')),


                       # Uncomment the next line to enable the admin:
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
                       url(r'^logout/$', views.logout_, name="logout"),

                       url(r'^$', views.base, name="base"),


                       # (r'^admin/(.*)', admin.site.root),


                       url(r'^event/export/', export, name="event_ics_export"),


                       url(r'^user/password/reset/$',
                           'django.contrib.auth.views.password_reset',
                           {'post_reset_redirect': '/user/password/reset/done/'},
                           name="password_reset"),
                       (r'^user/password/reset/done/$',
                        'django.contrib.auth.views.password_reset_done'),
                       (r'^user/password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                        'django.contrib.auth.views.password_reset_confirm',
                        {'post_reset_redirect': '/user/password/done/'}),
                       (r'^user/password/done/$',
                        'django.contrib.auth.views.password_reset_complete'),
                       (r'^summernote/', include('django_summernote.urls')),
                        url(r'^changeLanguage/(?P<language_code>\w+)', views.changeLanguage ,name="changeLanguage"),

)
if settings.DEBUG:
    urlpatterns += patterns(
        (r'^site_media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': MEDIA_ROOT, 'show_indexes': True}), )

DNM/apps/static_pages/models.py
__author__ = 'eaura'
from django.utils.translation import ugettext as _
from django.db import models

class PageText(models.Model):
    identifier = models.CharField(max_length=30)
    text = models.TextField(verbose_name=_('Text'))

DNM/apps/gallery/forms.py
from django import forms
from django.core.exceptions import ValidationError

from DNM.apps.gallery.models import Album


class AlbumForm(forms.ModelForm):



    class Meta:
        fields = ['title','description']
        model = Album

DNM/apps/klotter/forms.py
from django.forms import ModelForm
from DNM.apps.klotter.models import KlotterPost
from django_summernote.widgets import SummernoteWidget
__author__ = 'eaura'


class KlotterForm(ModelForm):
    class Meta:
        exclude = ('member','parent')
        model = KlotterPost
        widgets = {
            'text': SummernoteWidget(attrs={ 'width': '100%'}),
        }

DNM/apps/news/events/forms.py
from DNM.apps.news.forms import *
from DNM.apps.news.events.models import *
from functools import partial
from django.forms import DateTimeInput,DateTimeField



DateTimeInput = partial(DateTimeInput, {'class': 'datepicker'})

class EventForm(NewsForm):
    date = DateTimeField(input_formats=('%d.%m.%Y %H:%M',),widget=DateTimeInput(format="%d.%m.%Y %H:%M"))
    deadline = DateTimeField(input_formats=('%d.%m.%Y %H:%M',),widget=DateTimeInput(format="%d.%m.%Y %H:%M"))

    class Meta:
        exclude = ('member','madeByAdmin')
        model = Event
        widgets = {
            'description': SummernoteWidget(attrs={ 'width': '100%'}),

        }

DNM/apps/news/forms.py
from django.forms import ModelForm
from django.db import models
from django.utils import timezone
from django import forms
from datetime import timedelta
from DNM.apps.news.models import News
from django.contrib.admin.widgets import FilteredSelectMultiple
from django_summernote.widgets import SummernoteWidget

class NewsForm(ModelForm):
    class Meta:
        exclude = ('member',)
        model = News
        widgets = {
            'description': SummernoteWidget(attrs={'width': '100%'}),
        }

DNM/apps/gallery/views.py
# gallery/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect

from django.views.generic import View, ListView
from django.views.generic.edit import CreateView,UpdateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils import timezone

from braces.views import (
    AjaxResponseMixin,
    JSONResponseMixin,
    LoginRequiredMixin,
    SuperuserRequiredMixin,
)

from DNM.apps.gallery.models import Album, Photo
from DNM.apps.gallery.forms import AlbumForm
from django.utils.translation import ugettext as _
class AlbumCreate(CreateView):
    form_class = AlbumForm
    success_url = '/gallery/album_list/'
    template_name = 'gallery/album_new.html'


class AlbumEdit(UpdateView):
    form_class = AlbumForm
    success_url = '/gallery/album_list/'
    template_name = 'gallery/album_edit.html'
    def get_queryset(self,**kwargs):
           # query_set = super(ModelxUpdateView, self).get_queryset().filter(user=self.request.user)
           query_set = Album.objects.filter(pk=self.kwargs['pk'])
           return query_set

class AlbumListView(ListView):

    model = Album

    def get_context_data(self, **kwargs):
        context = super(AlbumListView, self).get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context

class PhotoListView(ListView):

    model = Photo


    def get_queryset(self, **kwargs):
        return Photo.objects.filter(album=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        context = super(PhotoListView, self).get_context_data(**kwargs)
        album = Album.objects.get(pk=self.kwargs['id'])
        context['album'] = album
        context['now'] = timezone.now()
        return context

class AjaxPhotoUploadView(LoginRequiredMixin,
                    SuperuserRequiredMixin,
                    JSONResponseMixin,
                    AjaxResponseMixin,
                    View):
    """
    View for uploading photos via AJAX.
    """
    def post_ajax(self, request, *args, **kwargs):
        try:
            album = Album.objects.get(pk=kwargs.get('pk'))
        except Album.DoesNotExist:
            error_dict = {'message': _('Fann inte albumet.')}
            return self.render_json_response(error_dict, status=404)

        uploaded_file = request.FILES['file']
        photo = Photo.objects.create(album=album, file=uploaded_file)
        photo.save()
        response_dict = {
            'message': _('Filen laddades upp!'),
        }

        return self.render_json_response(response_dict, status=200)


def set_cover_photo(request, album_id,photo_id):
    album =Album.objects.get(pk=album_id)
    album.cover_photo=Photo.objects.get(pk=photo_id)
    album.save()

    return HttpResponseRedirect(reverse('gallery:album_edit', args=(album_id)))

DNM/apps/klotter/views.py
# coding=utf-8
# -*- coding: utf-8 -*-
from django.contrib.auth import get_user
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from endless_pagination.decorators import page_template

from DNM.apps.klotter.forms import KlotterForm
from DNM.apps.klotter.models import KlotterPost, KlotterVote
from django.utils.translation import ugettext as _

__author__ = 'eaura'


@login_required
@page_template('klotter/klotter_page.html')  # just add this decorator
def klotterplanket(request,template='klotter.html', extra_context=None):

    if request.method == 'POST':
        form = KlotterForm(request.POST, instance=KlotterPost())
        if form.is_valid():
            klotter = form.save(commit=False)
            klotter.member = get_user(request)
            if request.POST.get("parent")!=u'None':
                parent = KlotterPost.objects.get(pk=request.POST.get("parent"))
                klotter.parent = parent
            messages.add_message(request, messages.SUCCESS, _('Kommentar sparad'))
            klotter.save()
        else:
            messages.add_message(request, messages.ERROR, _(u'Kunde inte spara inlägg. Kolla att alla obligatoriska fält är ifyllda'))

    klotter_list = [node.get_descendants(include_self=True)
         for node in KlotterPost.objects.filter(level__lte=0)]
    klotter = KlotterPost()
    if not get_user(request).grad.isGuest():
        klotter.writer = get_user(request).get_full_name
    form = KlotterForm(instance=klotter)

    context = {'nodes': klotter_list, 'form': form}
    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


@login_required
def vote(request, klotter_id):
    klotter = KlotterPost.objects.get(pk=klotter_id)
    vote, created =  KlotterVote.objects.get_or_create(member = request.user, klotter = klotter)
    if not created:
        messages.add_message(request, messages.ERROR, _(u'En röst per medlem'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))
    else:
        vote.klotter_id=klotter_id
        KlotterVote.save(vote)
        messages.add_message(request, messages.SUCCESS, _(u'Röst sparad'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))

@login_required
def comment(request, klotter_id):
    klotter = KlotterPost()
    if not get_user(request).grad.isGuest():
        klotter.writer = get_user(request).get_full_name
    form = KlotterForm(instance=klotter)
    context =  {'form' :form,'klotter_id':klotter_id}
    return render(request, 'klotter/writeComment.html', context)

@login_required
def new(request):
    return comment(request, None)

@login_required
def edit(request, klotter_id):
    klotter=KlotterPost.objects.get(pk=klotter_id)
    if klotter.member_id != get_user(request).id:
        messages.add_message(request, messages.ERROR, _(u'Du kan inte redigera andras inlägg'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))

    if request.method == 'POST':
        form = KlotterForm(request.POST, instance=klotter)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, _(u'Inlägg redigerat'))
        else:
            messages.add_message(request, messages.ERROR, _(u'Kunde inte spara inlägg. Kolla att alla obligatoriska fält är ifyllda'))
        return HttpResponseRedirect(reverse('klotter:klotterplanket'))

    else:

        form = KlotterForm(instance=klotter)
    context =  {'form' :form,'klotter_id':klotter_id}
    return render(request, 'klotter/editComment.html', context)

DNM/apps/news/views.py
# coding=utf-8
# -*- coding: utf-8 -*-
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required,user_passes_test
from django.contrib import messages
from django.contrib.auth import get_user
from DNM.apps.news.models import News

from DNM.apps.news.forms import NewsForm
from django.utils.translation import ugettext as _

@login_required
@user_passes_test(lambda u: u.title and u.title.styrelsePost or u.is_superuser )
def edit(request, news_id):
    if news_id == u'None':
        news = News()
        form = NewsForm(instance=news)
        form = NewsForm()
    else:
        news = News.objects.get(pk=news_id)
        form = NewsForm(instance=news)
    return render_to_response('news/edit.html', {'form': form, 'news': news}, RequestContext(request))

@login_required
def view(request, news_id):
    news = News.objects.get(pk=news_id)
    return render_to_response('news/view.html', { 'news': news}, RequestContext(request))

@login_required
@user_passes_test(lambda u: u.title and u.title.styrelsePost or u.is_superuser )
def save(request, news_id):
    if request.method == 'POST':
        if news_id == u'None':
            form = NewsForm(request.POST)
        else:
            news = News.objects.get(pk=news_id)
            form = NewsForm(request.POST, instance=news)
        if form.is_valid():
            news = form.save(commit=False)
            news.member=get_user(request)
            news.save()
            messages.add_message(request, messages.SUCCESS, _('Nyhet sparad'))
            return render_to_response('news/view.html', {'news': news}, RequestContext(request))
    else:
        form = NewsForm
    news=News()
    c = {'form': form,'news': news}
    messages.add_message(request, messages.ERROR, _(u'Åtgärden misslyckades'))
    return render_to_response('news/edit.html', c, RequestContext(request))


@login_required
@user_passes_test(lambda u: u.title or u.is_superuser )
def delete(request, news_id):
    news = News.objects.get(pk=news_id)
    News.delete(news)
    messages.add_message(request, messages.SUCCESS, _('Nyhet borttagen'))
    return HttpResponseRedirect(reverse('base'))

DNM/templates/klotter/editComment.html
{% load widget_tweaks %}
{% load i18n %}

<div class="modal-dialog">
    <div class="modal-content">
        <form action="{% url 'klotter:edit' klotter_id  %}" method="post">{% csrf_token %}

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="comment_modal_{{ klotter_id }}_label">{% trans "Redigera kommentar"%}</h4>
            </div>
            <div class="modal-body">

                {% csrf_token %}

                 {% for field in form %}
                    <div class="form-group {% if field.errors %} has-error {% endif %}">
                        <label>{{ field.label }}{% if field.field.required %} * {% endif %}{{ field.errors }}</label>
                        {% if field|widget_type == 'summernotewidget' %}
                            {{ field }}{{ field.errors }}
                        {% else %}
                            {{ field|add_class:"form-control" }}{{ field.errors }}
                        {% endif %}
                    </div>
                {% endfor %}


            </div>
            <div class="modal-footer">
                <input class="btn btn-primary" type="submit" value="{% trans "Skicka"%}"/>
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Stäng"%}</button>
            </div>
        </form>
    </div>
    <!-- /.modal-content -->
</div><!-- /.modal-dialog -->

DNM/templates/klotter/klotter_page.html
{% load mptt_tags %}
{% load endless %}
{% load i18n %}
{% if nodes %}
    <hr>
    {% paginate nodes %}
    {% for node in nodes %}
        {% recursetree node %}
            <div id="comment_{{ node.id }}">
                <div class="panel panel-default">
                    <div class="panel-body">
                        {{ node.text|safe }}
                    </div>
                    <div class="panel-footer">
                        {% if node.member.grad.hasImage %}
                            <a href={% url 'UserInformation:profile' node.member.id %}>
                                {{ node.writer }}</a> {{ node.created|date:"d.m.Y H:i" }}
                            <div style="display:inline-block">
                                <form id="upVote_{{ node.id }}" class="form-inline"
                                      action="{% url 'klotter:vote' node.id %}"
                                      method="post">
                                    {% csrf_token %}
                                    |
                                    {% if user in node.getUpVoters %}
                                        <i class="fa fa-beer icon-beer-full"></i>
                                    {% else %}
                                        <a href="#" onclick="document.getElementById('upVote_{{ node.id }}').submit();">
                                            <i class="fa fa-beer"></i>
                                        </a>
                                    {% endif %}
                                    {{ node.upVotes|length }}
                                </form>
                            </div>

                        {% else %}
                            <a href={% url 'UserInformation:profile' node.member.id %}>
                                {{ node.writer }}</a> {{ node.created|date:"d.m.Y H:i" }}
                            <div style="display:inline-block">
                                <form id="upVote_{{ node.id }}" class="form-inline"
                                      action="{% url 'klotter:vote' node.id %}"
                                      method="post">
                                    {% csrf_token %}
                                    |
                                    {% if user in node.getUpVoters %}
                                        <i class="fa fa-beer icon-beer-full"></i>
                                    {% else %}
                                        <a href="#" onclick="document.getElementById('upVote_{{ node.id }}').submit();">
                                            <i class="fa fa-beer"></i>
                                        </a>
                                    {% endif %}
                                    {{ node.upVotes|length }}
                                </form>
                            </div>

                        {% endif %}



                        <a class="btn btn-default btn-xs" href="#" data-toggle="modal" data-target="#ajax-modal"
                           data-href="{% url 'klotter:comment' node.id %}">
                            {% trans "Kommentera"%}
                        </a>
                        {% if node.member == user %}
                            <a class="btn btn-default btn-xs" href="#" data-toggle="modal" data-target="#ajax-modal"
                               data-href="{% url 'klotter:edit' node.id %}">
                                {% trans "Redigera inlägg"%}
                            </a>
                        {% endif %}
                        {% if node.get_descendant_count != 0 %}
                            <button id="toggle_comments_{{ node.id }}" class="btn btn-default btn-xs">
                                {% trans "Visa/Dölj kommentarer"%} ({{ node.get_descendant_count }})
                            </button>
                        {% endif %}
                    </div>
                </div>

                <div id="{{ node.id }}_replies">
                    {% if not node.is_leaf_node %}
                        <ul class="children">
                            {{ children }}
                        </ul>
                    {% endif %}

                </div>
            </div>
        {% endrecursetree %}
    {% endfor %}
    {% show_more %}

{% else %}
    <p>{% trans "Inga inlägg"%}.</p>
{% endif %}

{% block scripts %}
    <script type="text/javascript">
        $(function () {
            $("[rel='tooltip']").tooltip();
        });
    </script>
{% endblock %}

DNM/templates/klotter/writeComment.html
{% load widget_tweaks %}
{% load i18n %}
<div class="modal-dialog">
    <div class="modal-content">
        <form action="{% url 'klotter:klotterplanket' %}" method="post">{% csrf_token %}

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="comment_modal_{{ klotter_id }}_label">{% trans "Ny kommentar"%}</h4>
            </div>
            <div class="modal-body">

                {% csrf_token %}

                <input type="hidden" name="parent" id="parent" value="{{ klotter_id }}">
                {% for field in form %}
                    <div class="form-group {% if field.errors %} has-error {% endif %}">
                        <label>{{ field.label }}{% if field.field.required %} * {% endif %}{{ field.errors }}</label>
                        {% if field|widget_type == 'summernotewidget' %}
                            {{ field }}{{ field.errors }}
                        {% else %}
                            {{ field|add_class:"form-control" }}{{ field.errors }}
                        {% endif %}
                    </div>
                {% endfor %}

            </div>
            <div class="modal-footer">
                <input class="btn btn-primary" type="submit" value="{% trans "Skicka"%}"/>
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans "Stäng"%}</button>
            </div>
        </form>
    </div>
    <!-- /.modal-content -->
</div><!-- /.modal-dialog -->